'use strict';
window.LESSON = {
  id:'u2-day2-industrial-transformation',
  endpoint:'https://script.google.com/macros/s/AKfycbxuvOZujw3FrxJeGSETDOT9AxfE_aXS522FXwbDoqtiGJ-izMWgpvpdYPR6NJoWnHnVdg/exec',
  token:'ea445c98-c0d1-45c7-b2be-e7d94d46e50f18bf168a-98d1-414b-bd4a-087670e866be',
  // Application token for the explicitly requested username-only student flow.
  // This is not a Google credential or student authentication.
  gdp:[
    [1270,1192,null],[1500,1697,null],[1600,1691,null],[1700,2412,null],
    [1750,2702,null],[1800,3343,2545.488],[1820,3306,2674.048],
    [1850,4332,3631.82],[1865,5333,4637.1592],[1870,5829,4803.0016],
    [1900,7594,8037.5712],[1913,8212,10107.969407089222],
    [1920,7017,10152.92710876304],[1950,11061,15240],
    [2000,31946.036339441373,45886.47049828895]
  ],
  lighting:[
    [1800,'Tallow candle',5.37,'5.4 hours'],[1830,'Tallow candle',3,'3 hours'],
    [1900,'Carbon-filament lamp',.220431,'13.2 minutes'],
    [1910,'Carbon-filament lamp',.092096,'5.5 minutes'],
    [1920,'Filament lamp',.013538,'48.7 seconds'],
    [1950,'Filament lamp',.001883,'6.8 seconds'],
    [1992,'Compact fluorescent lamp',.000119,'0.43 seconds']
  ],
  metrics:[
    {title:'Literacy',stat:'20% → 10.7% illiterate',text:'United States, 1870 to 1900, ages 10 and older. These historical categories describe basic reading/writing, not modern functional literacy. In 1900 the reported rates were 6.2% for White people and 44.5% for Black people. Race and class are different dimensions; unequal educational opportunity matters.',source:'NCES, 120 Years of Literacy.'},
    {title:'Schooling',stat:'51% → 75% enrolled',text:'United States, ages 5–19, 1900 to 1940. Enrollment is not the same as attendance, school quality, or graduation. Notice that the second date extends beyond our 1865–1920 focus.',source:'NCES, 120 Years of Literacy.'},
    {title:'Poverty',stat:'A series beginning in 1959',text:'The U.S. Census official poverty series begins in 1959. It cannot supply a comparable poverty rate for 1900. Its income thresholds measure one kind of deprivation; they do not capture every aspect of hardship. Later poverty measures are an extension of our inquiry, not direct evidence for the Gilded Age.',source:'U.S. Census, historical poverty tables.'},
    {title:'Energy per person',stat:'About 102 → 126 million Btu',text:'United States, 1850 to 1900. Calculation: EIA estimated total primary energy divided by Census population. Totals were 2.357 and 9.587 quadrillion Btu; populations were 23,191,876 and 76,212,168. These estimates exclude direct mechanical water power and do not measure a household’s energy bill or useful output.',source:'EIA Table E1; U.S. Census 1850 and 1900.'},
    {title:'Travel',stat:'Coast-to-coast in about a week',text:'The first transcontinental railroad connection was completed in 1869. The New York–San Francisco journey could take about seven days, compared with months on an overland wagon journey. Route, fare, safety, and access mattered; this is not a universal travel-time average.',source:'ASCE, Union Pacific Railroad historical landmark.'},
    {title:'Information delivery',stat:'A wire crossed the continent in 1861',text:'The transcontinental telegraph linked the eastern and western United States in 1861. Messages no longer had to travel physically the entire distance. Rapid transmission did not guarantee immediate delivery to every home, and service had a cost.',source:'National Park Service, Pony Express / telegraph history.'},
    {title:'Paid work hours',stat:'55 scheduled / 49 paid hours',text:'U.S. manufacturing in 1915: about 55 scheduled hours in a week, compared with about 49 paid hours for production workers. These measures differ. Neither includes all farm work, unpaid household labor, or everyone’s leisure time. We cannot subtract these numbers from 168 and call the remainder “free time.”',source:'BLS, The life of American workers in 1915.'},
    {title:'Household infrastructure',stat:'Available did not mean universal',text:'The Vanderbilt mansion, completed in 1899, had electricity, hot and cold running water, and flush toilets. This documented wealthy household shows what was possible, not what every home had. Infrastructure required equipment, local systems, and money.',source:'National Park Service, Vanderbilt Mansion audio tour.'}
  ],
  vocab:[
    ['Industrialization','A shift toward machine production, new energy sources, and reorganized work.'],
    ['GDP per capita','The value of economic production divided by population.'],
    ['Life expectancy','An estimate of average years of life under a population’s death rates.'],
    ['Infant mortality','Deaths before age one, usually measured per 1,000 live births.'],
    ['Productivity','Output produced for a given amount of input, such as labor time.'],
    ['Infrastructure','The shared systems and facilities that support daily life.'],
    ['Inequality','Unequal distribution of resources or opportunities among people.'],
    ['Mechanism','The process through which a cause can produce an effect.']
  ],
  definitions:{
    'Industrial Revolution':'The long shift toward machine production, new sources of power, and factory organization, beginning in eighteenth-century Britain.',
    industrialization:'The process of expanding machine production, industrial energy use, and new forms of organizing work.',
    capability:'An ability or possibility: what people are able to do.',
    transformation:'A major change in how something works or is organized.',
    institutions:'Durable rules and organizations that shape people’s choices, such as laws, schools, and systems of ownership.',
    production:'The process of making goods or providing services.',
    'GDP per capita':'Gross domestic product divided by population: average economic output per person, not an individual’s income.',
    'purchasing power':'What money can buy. These adjustments help compare output across places with different prices.',
    'life expectancy':'Estimated average years of life if a population experienced the death rates of a particular period.',
    'infant mortality':'Death before age one; the rate is usually deaths per 1,000 live births.',
    'lumen-hours':'A measure of light service: brightness in lumens multiplied by time in hours.',
    'top 10%':'The tenth of a population with the highest incomes in the comparison.',
    'bottom 50%':'The half of a population with the lowest incomes in the comparison.',
    output:'The goods or services produced.',
    average:'A summary found by dividing a total by the number of people or items; it can hide differences.',
    estimates:'Values calculated from incomplete evidence or a model; they carry uncertainty.',
    benchmarks:'Selected reference values used for comparisons.',
    observations:'Information recorded or measured, rather than assumed.',
    pattern:'A recurring feature or direction in evidence.',
    trend:'The broad direction of change over time.',
    evidence:'Information used to support or question a claim.',
    claim:'A statement or explanation that needs support.',
    mechanism:'The process connecting a possible cause to an outcome.',
    mechanisms:'The processes connecting possible causes to outcomes.',
    outcome:'A result or consequence.',
    outcomes:'Results or consequences.',
    inequality:'Unequal distribution of resources or opportunities.',
    distribution:'How a total is divided among people or groups.',
    infrastructure:'Shared systems and facilities, such as roads, water networks, and electricity lines.',
    productivity:'Output for each unit of input, such as output per hour of labor.',
    metric:'A specific measure used to describe or compare something.',
    metrics:'Specific measures used to describe or compare things.',
    enrolled:'Officially registered to attend a school or program.',
    literacy:'The ability to read and write; different measures use different standards.',
    illiterate:'Classified as unable to read or write under a source’s definition.',
    'functional literacy':'The ability to use reading and writing effectively in everyday tasks.',
    thresholds:'Cutoff points used to define a category.',
    deprivation:'A lack of resources needed for life or participation.',
    'primary energy':'Energy in its initial forms, before conversion into electricity or other usable forms.',
    Btu:'British thermal unit, a measure of energy.',
    quadrillion:'One thousand trillion: 1,000,000,000,000,000.',
    transmission:'Sending information from one place to another.',
    scheduled:'Planned or required by a timetable.',
    relative:'Described in comparison with something else.',
    absolute:'Described on its own scale, rather than as a position compared with others.',
    security:'Stability or protection against losing important resources and opportunities.',
    participation:'Being able to take part and have a voice.',
    implication:'Something the evidence suggests may follow.',
    qualify:'Limit a claim to the conditions the evidence actually supports.',
    corroborate:'Check whether another independent source supports a statement.',
    perspective:'A point of view shaped by a person’s position and experience.',
    'Gilded Age':'A name commonly used for the late nineteenth-century United States, associated with rapid growth and sharp inequalities.',
    'steam engines':'Machines that convert energy from heated water into mechanical motion.',
    'cotton gin':'A machine that separates seeds from cotton fibers.',
    labor:'Human effort used to produce goods or services.',
    access:'The ability to obtain or use something.',
    capacity:'The amount a person or system can do or produce.',
    unevenly:'At different rates or to different degrees across people or places.',
    'reconstructions':'Estimates of past conditions built from surviving evidence.'
  },
  sources:[
    ['Maddison Project Database 2023','https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2023?lang=en','GDPpc sheet, GBR and USA. 2011 international dollars. Early GBR coverage changes; selected benchmarks only. Credit underlying country sources as listed in the database.'],
    ['William D. Nordhaus, Do Real-Output and Real-Wage Measures Capture Reality? The History of Lighting Suggests Not','https://www.nber.org/system/files/chapters/c6064/c6064.pdf','Table 1.6, printed pages 52–53. Labor hours per 1,000 lumen-hours; selected technologies and changing wage measures.'],
    ['CDC/NCHS, life expectancy comparison','https://www.cdc.gov/mmwr/preview/mmwrhtml/mm6019a5.htm','47.3 (1900 registration states) and 76.8 (2000 national).'],
    ['CDC/NCHS, infant mortality','https://www.cdc.gov/nchs/products/databriefs/db09.htm','Approximate early rate and 6.89 in 2000; infant deaths per 1,000 live births.'],
    ['NCES, 120 Years of Literacy','https://nces.ed.gov/naal/lit_history.asp','Historical illiteracy and enrollment; age definitions matter.'],
    ['NCES, 120 Years of American Education','https://nces.ed.gov/pubs93/93442.pdf','Statistical portrait underlying the historical education summary.'],
    ['U.S. Census, historical poverty tables','https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html','Official series begins in 1959; no comparable 1900 rate shown.'],
    ['EIA, estimated primary energy, Table E1','https://www.eia.gov/totalenergy/data/annual/txt/ptb1601.html','1850 and 1900 totals divided by Census population; direct mechanical water power excluded.'],
    ['U.S. Census, 1850 population','https://www.census.gov/programs-surveys/decennial-census/decade.1850.html','23,191,876.'],
    ['U.S. Census, 1900 population','https://www.census.gov/programs-surveys/decennial-census/decade.1900.html','76,212,168.'],
    ['ASCE, Union Pacific Railroad','https://www.asce.org/about-civil-engineering/history-and-heritage/historic-landmarks/union-pacific-railroad/','Historic landmark summary; approximately seven-day transcontinental travel.'],
    ['NPS, Pony Express history','https://www.nps.gov/poex/learn/historyculture/index.htm','Transcontinental telegraph completed in 1861.'],
    ['BLS, The life of American workers in 1915','https://www.bls.gov/opub/mlr/2016/article/the-life-of-american-workers-in-1915.htm','Scheduled manufacturing hours and paid production-worker hours are different measures.'],
    ['NPS, Vanderbilt Mansion audio tour','https://www.nps.gov/vama/learn/historyculture/audio-tour-of-the-mansion.htm','Documented household conveniences, 1899; not representative of all households.'],
    ['World Inequality Report 2022, Chapter 2','https://wir2022.wid.world/chapter-2/','Figure 2.2: global top-10% / bottom-50% average-income ratio; not percentages or U.S. income shares.'],
    ['TED-Ed, How inventions change history (for better and for worse)','https://ed.ted.com/lessons/how-inventions-change-history-for-better-and-for-worse-kenneth-c-davis','Opening cotton-gin example; publisher description verified.'],
    ['National Archives, cotton gin patent','https://www.archives.gov/education/lessons/cotton-gin-patent','Patent issued 1794; invention developed in 1793.']
  ]
};
